version: "3.8"

networks:
  banking-audit-network:
    driver: bridge

services:
  orderer.bankingaudit.com:
    container_name: orderer.bankingaudit.com
    image: hyperledger/fabric-orderer:2.4.9
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_KAFKA_TOPIC_REPLICATIONFACTOR=1
      - ORDERER_KAFKA_VERBOSE=true
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: orderer
    volumes:
      - ./genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ./crypto-config/ordererOrganizations/bankingaudit.com/orderers/orderer.bankingaudit.com/msp:/var/hyperledger/orderer/msp
      - ./crypto-config/ordererOrganizations/bankingaudit.com/orderers/orderer.bankingaudit.com/tls/:/var/hyperledger/orderer/tls
      - orderer.bankingaudit.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050
    networks:
      - banking-audit-network

  peer0.bankingaudit.com:
    container_name: peer0.bankingaudit.com
    image: hyperledger/fabric-peer:2.4.9
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=banking-audit-network_network
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_ID=peer0.bankingaudit.com
      - CORE_PEER_ADDRESS=peer0.bankingaudit.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.bankingaudit.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.bankingaudit.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.bankingaudit.com:7051
      - CORE_PEER_LOCALMSPID=BankingAuditMSP
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/bankingaudit.com/peers/peer0.bankingaudit.com/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/bankingaudit.com/peers/peer0.bankingaudit.com/tls:/etc/hyperledger/fabric/tls
      - peer0.bankingaudit.com:/var/hyperledger/production
      - ./chaincode:/opt/gopath/src/github.com/hyperledger/fabric/peer/chaincode
      - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 7051:7051
      - 7052:7052
    depends_on:
      - orderer.bankingaudit.com
    networks:
      - banking-audit-network

volumes:
  orderer.bankingaudit.com:
  peer0.bankingaudit.com:
